// Built to be loaded with BCC (Python).

#include <uapi/linux/ptrace.h>
#include <linux/sched.h>
#include <linux/types.h>
#include <linux/tracepoint.h>
#include <linux/ptrace.h>

#define ARGV_LEN 128
#define COMM_LEN TASK_COMM_LEN

struct event_t {
    u64 ts_ns;
    u32 pid;
    u32 tgid;
    u32 uid;
    char comm[COMM_LEN];
    char argv[ARGV_LEN];
};

BPF_PERF_OUTPUT(events);

// Tracepoint args structure for sys_enter_execve
// This is auto-generated by BCC for tracepoints
TRACEPOINT_PROBE(syscalls, sys_enter_execve) {
    struct event_t evt = {};
    u64 pidtgid = bpf_get_current_pid_tgid();
    evt.tgid = pidtgid & 0xffffffff;
    evt.pid  = pidtgid >> 32;
    evt.ts_ns = bpf_ktime_get_ns();
    evt.uid = bpf_get_current_uid_gid() & 0xffffffff;

    // get comm (process name)
    bpf_get_current_comm(&evt.comm, sizeof(evt.comm));

    // Read filename from tracepoint args
    // args->filename is available from the tracepoint context
    bpf_probe_read_user_str(&evt.argv, sizeof(evt.argv), (void *)args->filename);

    // submit event to user-space via perf buffer
    events.perf_submit(args, &evt, sizeof(evt));

    return 0;
}